### ISSUE TITLE
NullPointerException if you use inheritance in Java interface and @Override

### ISSUE THREAD

**Issue by lofidewanto** [DominoKit/domino-rest#23]
Following example:

```
@RequestFactory
public interface PersonClient extends PersonApi {

	@Override
	@GET
	@Path(PersonEndpoint.PERSON_LIST)
	List<PersonDto> getPersons();

	@Override
	@GET
	@Path(PersonEndpoint.PERSON_WITH_ERROR_LIST)
	List<ErrorDto> getPersonsWithError() throws PersonException;
}
```
with
```
public interface PersonApi {

	List<PersonDto> getPersons();

	List<ErrorDto> getPersonsWithError() throws PersonException;

}
```
You'll get NullPointerException:

```
[INFO] -------------------------------------------------------------
[ERROR] COMPILATION ERROR : 
[INFO] -------------------------------------------------------------
[ERROR] error while creating source file java.lang.NullPointerException
      at org.dominokit.domino.rest.apt.RequestFactorySourceWriter.getPath(RequestFactorySourceWriter.java:419)
      at org.dominokit.domino.rest.apt.RequestFactorySourceWriter.constructor(RequestFactorySourceWriter.java:310)
      at org.dominokit.domino.rest.apt.RequestFactorySourceWriter.makeRequestClass(RequestFactorySourceWriter.java:195)
      at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
      at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1374)
      at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
      at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
      at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
      at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
      at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
      at org.dominokit.domino.rest.apt.RequestFactorySourceWriter.asTypeBuilder(RequestFactorySourceWriter.java:65)
      at org.dominokit.domino.rest.apt.RequestFactoryProcessingStep.generateFactory(RequestFactoryProcessingStep.java:55)
      at org.dominokit.domino.rest.apt.RequestFactoryProcessingStep.process(RequestFactoryProcessingStep.java:46)
      at org.dominokit.domino.rest.apt.RequestFactoryProcessor.process(RequestFactoryProcessor.java:42)
```

**Comment by lofidewanto** [comment]
Thanks a lot, now it's working in my example: https://github.com/gwtboot/domino-rest-enum-date
