### ISSUE TITLE
RequestFactorySourceWriter.isRequestBody triggers a NullPointerException when using annotations

### ISSUE THREAD

**Issue by natros** [DominoKit/domino-rest#50]
RequestFactorySourceWriter.isRequestBody triggers a `NullPointerException` when using any kind of annotation. I'm trying to use validation with `@Valid` from `jakarta.validation:jakarta.validation-api:2.0.2` or `javax.validation:validation-api:2.0.1.Final` to validate a DTO.

```java
@RequestFactory
@Path("/users")
@Produces("application/json")
@Consumes("application/json")
public interface UserResource {
  //...
  @POST
  void addUser(@Valid UserDto dto);
}
```

```
error: error while creating source file java.lang.NullPointerException
        at org.dominokit.domino.rest.apt.RequestFactorySourceWriter.isRequestBody(RequestFactorySourceWriter.java:513)
        at org.dominokit.domino.rest.apt.RequestFactorySourceWriter.isBodyParameter(RequestFactorySourceWriter.java:496)
        at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:176)
        at java.base/java.util.ArrayList$ArrayListSpliterator.tryAdvance(ArrayList.java:1631)
        at java.base/java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:127)
        at java.base/java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:502)
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:488)
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
        at java.base/java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:150)
        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.base/java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:543)
        at org.dominokit.domino.rest.apt.RequestFactorySourceWriter.getRequestBeanType(RequestFactorySourceWriter.java:462)
        at org.dominokit.domino.rest.apt.RequestFactorySourceWriter.makeRequestClass(RequestFactorySourceWriter.java:385)
        at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
        at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1654)
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
        at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578)
        at org.dominokit.domino.rest.apt.RequestFactorySourceWriter.asTypeBuilder(RequestFactorySourceWriter.java:89)
        at org.dominokit.domino.rest.apt.RequestFactoryProcessingStep.generateFactory(RequestFactoryProcessingStep.java:55)
        at org.dominokit.domino.rest.apt.RequestFactoryProcessingStep.process(RequestFactoryProcessingStep.java:46)
        at org.dominokit.domino.rest.apt.RequestFactoryProcessor.process(RequestFactoryProcessor.java:44)
....
```

I'm using `org.dominokit:domino-rest-apt:1.0-rc.4-SNAPSHOT` with java 11.

**Comment by vegegoku** [comment]
this is weird, extra annotations should have effect on this, as a workaround you can add the `@RequestBody` to the UserDto arg.

and if you can prepare a small sample where i can reproduce this, it would be greate.

**Comment by natros** [comment]
Hope it helps

https://github.com/natros/domino-rest-npe

**Comment by vegegoku** [comment]
@natros thank you for the sample, it was of a great help.

it seems the problem is caused by the annotation value which is also annotated with `@Documented` which is according to its documentation means that this `@Valid` will become part of the `UserDto` contract, tested on java 11 fails the build due to how `typeMirror.toString()` returns the result.

without the `@Valid` annotation it returns `com.github.natros.domoni.rest.npe.UserDto` while with the annotation it returns `javax.validation.@Valid com.github.natros.domoni.rest.npe.UserDto`.

this leads to the fact that we should avoid using `TypeMirror.toString()` and instead we should use a different approach.

something like this

`((TypeElement)typeUtils.asElement(typeMirror)).getQualifiedName().toString();`
