### ISSUE TITLE
when You declare twice JAXRS resource using @ResourceList compiler fails

### ISSUE THREAD

**Issue by masterdany88** [DominoKit/domino-rest#52]
When I by mistake added twice same jaxrs resource:

```
@ResourceList({
        WifiRestResource.class,
        ReportsRestResourceFactory.class,
        ReportsRestResourceFactory.class
})

import org.dominokit.domino.rest.shared.request.service.annotations.ResourceList;

```

 I am getting compillation issue. Very generic. Very hard to guess whats wrong.

**Comment by vegegoku** [comment]
Can you please post the stack trace error here?

**Comment by masterdany88** [comment]
Error:java: error while creating source file javax.annotation.processing.FilerException: Attempt to recreate a file for type com.company.base.app.client.rest.ReportsRestResourceFactory
  	at com.sun.tools.javac.processing.JavacFiler.checkNameAndExistence(JavacFiler.java:522)
  	at com.sun.tools.javac.processing.JavacFiler.createSourceOrClassFile(JavacFiler.java:396)
  	at com.sun.tools.javac.processing.JavacFiler.createSourceFile(JavacFiler.java:378)
  	at dominojackson.shaded.com.squareup.javapoet.JavaFile.writeTo(JavaFile.java:114)
  	at dominojackson.shaded.org.dominokit.domino.apt.commons.AbstractProcessingStep.writeSource(AbstractProcessingStep.java:49)
  	at dominojackson.shaded.org.dominokit.domino.apt.commons.AbstractProcessingStep.lambda$writeSource$0(AbstractProcessingStep.java:63)
  	at java.util.Collections$SingletonList.forEach(Collections.java:4824)
  	at dominojackson.shaded.org.dominokit.domino.apt.commons.AbstractProcessingStep.writeSource(AbstractProcessingStep.java:61)
  	at org.dominokit.domino.rest.apt.ResourceListProcessingStep.lambda$generateFactory$0(ResourceListProcessingStep.java:61)
  	at java.util.ArrayList.forEach(ArrayList.java:1257)
  	at org.dominokit.domino.rest.apt.ResourceListProcessingStep.generateFactory(ResourceListProcessingStep.java:59)
  	at org.dominokit.domino.rest.apt.ResourceListProcessingStep.process(ResourceListProcessingStep.java:48)
  	at org.dominokit.domino.rest.apt.RequestFactoryProcessor.process(RequestFactoryProcessor.java:51)
  	at com.sun.tools.javac.processing.JavacProcessingEnvironment.callProcessor(JavacProcessingEnvironment.java:794)
  	at com.sun.tools.javac.processing.JavacProcessingEnvironment.discoverAndRunProcs(JavacProcessingEnvironment.java:705)
  	at com.sun.tools.javac.processing.JavacProcessingEnvironment.access$1800(JavacProcessingEnvironment.java:91)
  	at com.sun.tools.javac.processing.JavacProcessingEnvironment$Round.run(JavacProcessingEnvironment.java:1035)
  	at com.sun.tools.javac.processing.JavacProcessingEnvironment.doProcessing(JavacProcessingEnvironment.java:1176)
  	at com.sun.tools.javac.main.JavaCompiler.processAnnotations(JavaCompiler.java:1170)
  	at com.sun.tools.javac.main.JavaCompiler.compile(JavaCompiler.java:856)
  	at com.sun.tools.javac.main.Main.compile(Main.java:523)
  	at com.sun.tools.javac.api.JavacTaskImpl.doCall(JavacTaskImpl.java:129)
  	at com.sun.tools.javac.api.JavacTaskImpl.call(JavacTaskImpl.java:138)
  	at org.jetbrains.jps.javac.JavacMain.compile(JavacMain.java:207)
  	at org.jetbrains.jps.incremental.java.JavaBuilder.compileJava(JavaBuilder.java:493)
  	at org.jetbrains.jps.incremental.java.JavaBuilder.compile(JavaBuilder.java:345)
  	at org.jetbrains.jps.incremental.java.JavaBuilder.doBuild(JavaBuilder.java:270)
  	at org.jetbrains.jps.incremental.java.JavaBuilder.build(JavaBuilder.java:223)
  	at org.jetbrains.jps.incremental.IncProjectBuilder.runModuleLevelBuilders(IncProjectBuilder.java:1414)
  	at org.jetbrains.jps.incremental.IncProjectBuilder.runBuildersForChunk(IncProjectBuilder.java:1092)
  	at org.jetbrains.jps.incremental.IncProjectBuilder.buildTargetsChunk(IncProjectBuilder.java:1159)
  	at org.jetbrains.jps.incremental.IncProjectBuilder.buildChunkIfAffected(IncProjectBuilder.java:1053)
  	at org.jetbrains.jps.incremental.IncProjectBuilder.buildChunks(IncProjectBuilder.java:882)
  	at org.jetbrains.jps.incremental.IncProjectBuilder.runBuild(IncProjectBuilder.java:449)
  	at org.jetbrains.jps.incremental.IncProjectBuilder.build(IncProjectBuilder.java:190)
  	at org.jetbrains.jps.cmdline.BuildRunner.runBuild(BuildRunner.java:138)
  	at org.jetbrains.jps.cmdline.BuildSession.runBuild(BuildSession.java:297)
  	at org.jetbrains.jps.cmdline.BuildSession.run(BuildSession.java:130)
  	at org.jetbrains.jps.cmdline.BuildMain$MyMessageHandler.lambda$channelRead0$0(BuildMain.java:218)
  	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
  	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
  	at java.lang.Thread.run(Thread.java:748)
