### ISSUE TITLE
Exception during Serializer generation

### ISSUE THREAD

**Issue by FrankHossfeld** [DominoKit/domino-rest#72]
Using a POJO as key of a Map will crash the generation.

```
ERROR] error while creating source file org.dominokit.jackson.processor.TypeRegistry$TypeDeserializerNotFoundException: de.gishmo.bug.test.dto.PoJoA
  	at org.dominokit.jackson.processor.TypeRegistry.getKeyDeserializer(TypeRegistry.java:827)
  	at org.dominokit.jackson.processor.deserialization.FieldDeserializersChainBuilder.getBasicKeyDeserializer(FieldDeserializersChainBuilder.java:167)
  	at org.dominokit.jackson.processor.deserialization.FieldDeserializersChainBuilder.getKeyDeserializer(FieldDeserializersChainBuilder.java:162)
  	at org.dominokit.jackson.processor.deserialization.FieldDeserializersChainBuilder.getMapDeserializer(FieldDeserializersChainBuilder.java:153)
  	at org.dominokit.jackson.processor.deserialization.FieldDeserializersChainBuilder.getFieldDeserializer(FieldDeserializersChainBuilder.java:91)
  	at org.dominokit.jackson.processor.deserialization.FieldDeserializersChainBuilder.getInstance(FieldDeserializersChainBuilder.java:80)
  	at org.dominokit.jackson.processor.deserialization.DeserializerBuilder.buildDeserializerMethod(DeserializerBuilder.java:102)
  	at org.dominokit.jackson.processor.deserialization.DeserializerBuilder.buildDeserializer(DeserializerBuilder.java:63)
  	at org.dominokit.jackson.processor.deserialization.AptDeserializerBuilder.lambda$buildInitDeserializersMethod$8(AptDeserializerBuilder.java:581)
```

The attach small project produces the exception.

[test-rest.zip](https://github.com/DominoKit/domino-rest/files/6702328/test-rest.zip)

**Comment by vegegoku** [comment]
So this is actually an issue domino-jackson rather than in domino-rest and in domino-jackson there is a fixed set of mappers types for  map keys.

https://github.com/DominoKit/domino-jackson/blob/3f925e9a28d146b93e520f44de21f47ded9ec51e/domino-jackson-processor/src/main/java/org/dominokit/jackson/processor/TypeRegistry.java#L515

But maybe this can be implemented to allow custom (de)serializers.
